name: PlaybookExample
projectReferences:
  Playbook:
    path: ../Playbook.xcodeproj

options:
  createIntermediateGroups: true
  bundleIdPrefix: app.playbook-ui.Example
  deploymentTarget:
    iOS: 13.0

settings:
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGN_IDENTITY: "-"
  CODE_SIGN_STYLE: Manual

schemes:
  SamplePlaybook:
    build:
      targets:
        SamplePlaybook: all
    test:
      targets:
        - SampleSnapshot
      commandLineArguments:
        -AppleLanguages (en): true
      environmentVariables:
        SNAPSHOT_DIR: $(SOURCE_ROOT)/../Snapshots/Example

targets:
  SamplePlaybook:
    Example:
    type: application
    platform: iOS
    sources: SamplePlaybook
    dependencies:
      - target: SampleComponent
      - target: Playbook/Playbook
      - target: Playbook/PlaybookUI

  SampleSnapshot:
    type: bundle.unit-test
    platform: iOS
    sources:
      - SampleSnapshot
    dependencies:
      - target: SamplePlaybook
      - target: Playbook/PlaybookSnapshot

  SampleApp:
    type: application
    platform: iOS
    sources:
      - SampleApp
    dependencies:
      - target: SampleComponent

  SampleComponent:
    type: framework
    platform: iOS
    sources:
      - SampleComponent
